/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppStartRouteImport } from './routes/_app.start'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppLoadingRouteImport } from './routes/_app.loading'
import { Route as AppAuditsRouteImport } from './routes/_app.audits'
import { Route as AppAuditRouteImport } from './routes/_app.audit'
import { Route as AppReportPillarRouteImport } from './routes/_app.report.$pillar'
import { Route as AppEvidenceIdRouteImport } from './routes/_app.evidence.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStartRoute = AppStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppLoadingRoute = AppLoadingRouteImport.update({
  id: '/loading',
  path: '/loading',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditsRoute = AppAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportPillarRoute = AppReportPillarRouteImport.update({
  id: '/$pillar',
  path: '/$pillar',
  getParentRoute: () => AppReportRoute,
} as any)
const AppEvidenceIdRoute = AppEvidenceIdRouteImport.update({
  id: '/evidence/$id',
  path: '/evidence/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/audits': typeof AppAuditsRoute
  '/loading': typeof AppLoadingRoute
  '/report': typeof AppReportRouteWithChildren
  '/start': typeof AppStartRoute
  '/evidence/$id': typeof AppEvidenceIdRoute
  '/report/$pillar': typeof AppReportPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AppAuditRoute
  '/audits': typeof AppAuditsRoute
  '/loading': typeof AppLoadingRoute
  '/report': typeof AppReportRouteWithChildren
  '/start': typeof AppStartRoute
  '/evidence/$id': typeof AppEvidenceIdRoute
  '/report/$pillar': typeof AppReportPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/audit': typeof AppAuditRoute
  '/_app/audits': typeof AppAuditsRoute
  '/_app/loading': typeof AppLoadingRoute
  '/_app/report': typeof AppReportRouteWithChildren
  '/_app/start': typeof AppStartRoute
  '/_app/evidence/$id': typeof AppEvidenceIdRoute
  '/_app/report/$pillar': typeof AppReportPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/audits'
    | '/loading'
    | '/report'
    | '/start'
    | '/evidence/$id'
    | '/report/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/audits'
    | '/loading'
    | '/report'
    | '/start'
    | '/evidence/$id'
    | '/report/$pillar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/audit'
    | '/_app/audits'
    | '/_app/loading'
    | '/_app/report'
    | '/_app/start'
    | '/_app/evidence/$id'
    | '/_app/report/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/start': {
      id: '/_app/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AppStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loading': {
      id: '/_app/loading'
      path: '/loading'
      fullPath: '/loading'
      preLoaderRoute: typeof AppLoadingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audits': {
      id: '/_app/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AppAuditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report/$pillar': {
      id: '/_app/report/$pillar'
      path: '/$pillar'
      fullPath: '/report/$pillar'
      preLoaderRoute: typeof AppReportPillarRouteImport
      parentRoute: typeof AppReportRoute
    }
    '/_app/evidence/$id': {
      id: '/_app/evidence/$id'
      path: '/evidence/$id'
      fullPath: '/evidence/$id'
      preLoaderRoute: typeof AppEvidenceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppReportRouteChildren {
  AppReportPillarRoute: typeof AppReportPillarRoute
}

const AppReportRouteChildren: AppReportRouteChildren = {
  AppReportPillarRoute: AppReportPillarRoute,
}

const AppReportRouteWithChildren = AppReportRoute._addFileChildren(
  AppReportRouteChildren,
)

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppAuditsRoute: typeof AppAuditsRoute
  AppLoadingRoute: typeof AppLoadingRoute
  AppReportRoute: typeof AppReportRouteWithChildren
  AppStartRoute: typeof AppStartRoute
  AppEvidenceIdRoute: typeof AppEvidenceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppAuditsRoute: AppAuditsRoute,
  AppLoadingRoute: AppLoadingRoute,
  AppReportRoute: AppReportRouteWithChildren,
  AppStartRoute: AppStartRoute,
  AppEvidenceIdRoute: AppEvidenceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
